#!/usr/bin/env python3
"""Generate tools/chat_turn.sigil — the deployable, pre-composed serve tool.

sigil-serve compiles tool sources directly (no stdlib composition step), so the
committed chat_turn.sigil is a build artifact:

    frag_main.sigil  (module header, uses, tool_main plumbing)
      + frag_helpers.sigil  spliced at the {{HELPERS}} marker
      -> compose_with_stdlib(..., ["http", "kv"])
      -> tools/chat_turn.sigil

Run from the sigil-pi root:  python3 make_chat_turn.py
CI guard: tests/test_generated_in_sync.py regenerates and diffs.
"""
from pathlib import Path

import toolchain

PI_ROOT = Path(__file__).resolve().parent

MARKER = "// {{HELPERS}}"
BANNER = (
    "// GENERATED by make_chat_turn.py — DO NOT EDIT.\n"
    "// Source of truth: tools/frag_main.sigil + tools/frag_helpers.sigil\n"
    "// (composed with stdlib http + kv so sigil-serve can compile it directly).\n"
)


def generate() -> str:
    tools = PI_ROOT / "tools"
    main = (tools / "frag_main.sigil").read_text()
    helpers = (tools / "frag_helpers.sigil").read_text()
    assert MARKER in main, f"frag_main.sigil must contain the splice marker {MARKER}"
    spliced = main.replace(MARKER, helpers.rstrip() + "\n")
    # Resolved rather than assumed: generation inlines the PINNED stdlib, so
    # which toolchain answers here decides what lands in the committed
    # artifact. toolchain.resolve() raises with every path it tried when
    # there is none, which beats composing against whatever happens to sit
    # at ../SIGIL.
    _, compose_with_stdlib = toolchain.client()
    composed = compose_with_stdlib(
        spliced, ["http", "kv"], toolchain.resolve().stdlib_repo).text
    return BANNER + composed


if __name__ == "__main__":
    out = PI_ROOT / "tools" / "chat_turn.sigil"
    out.write_text(generate())
    print(f"wrote {out} ({len(out.read_text())} chars)")
